apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 907101249682.dkr.ecr.ap-southeast-2.amazonaws.com/myapp-repo
  newName: 907101249682.dkr.ecr.ap-southeast-2.amazonaws.com/myapp-repo
  newTag: f7be237e
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
